name: PHPUnit

on:
  pull_request:
    paths:
      - "**.php"
      - "phpunit.xml"
      - ".github/workflows/phpunit.yml"

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - uses: php-actions/composer@v6 # or alternative dependency management

      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: Scarlett
        with:
          version: 9.3.3
          php_version: 7.4
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
